apiVersion: ensurance.crane.io/v1alpha1
kind: NodeQOS
metadata:
  name: "waterline3"
  labels:
    app: "system"
spec:
  nodeQualityProbe:
    timeoutSeconds: 10
    nodeLocalGet:
      localCacheTTLSeconds: 60
  rules:
    - name: "cpu-usage"
      avoidanceThreshold: 2
      restoreThreshold: 2
      actionName: "eviction"
      strategy: "Preview"
      metricRule:
        name: "cpu_total_usage"
        value: 6000
